export const CALL_API = 'CALL_API';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE';

export const ACTIVATE_REQUEST = 'ACTIVATE_REQUEST';
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';
export const ACTIVATE_FAILURE = 'ACTIVATE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const COURSES_REQUEST = 'COURSES_REQUEST';
export const COURSES_SET = 'COURSES_SET';
export const COURSES_FAILURE = 'COURSES_FAILURE';
export const COURSE_MODERATORS_REQUEST = 'COURSE_MODERATORS_REQUEST';
export const COURSE_MODERATORS_SET = 'COURSE_MODERATORS_SET';
export const COURSE_MODERATORS_FAILURE = 'COURSE_MODERATORS_FAILURE';
export const COURSE_ADD_REQUEST = 'COURSE_ADD_REQUEST';
export const COURSE_ADD_SUCCESS = 'COURSE_ADD_SUCCESS';
export const COURSE_ADD_FAILURE = 'COURSE_ADD_FAILURE';
export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_FAILURE = 'COURSE_UPDATE_FAILURE';

export const LECTURES_REQUEST = 'LECTURES_REQUEST';
export const LECTURES_SET = 'LECTURES_SET';
export const LECTURES_FAILURE = 'LECTURES_FAILURE';
export const LECTURE_ADD_REQUEST = 'LECTURES_ADD_REQUEST';
export const LECTURE_ADD_SUCCESS = 'LECTURES_ADD_SUCCESS';
export const LECTURE_ADD_FAILURE = 'LECTURES_ADD_FAILURE';

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SET = 'COMMENTS_SET';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';

export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_UPDATE = 'COMMENT_UPDATE';

export const ACCOUNT_REQUEST = 'ACCOUNT_REQUEST';
export const ACCOUNT_SET = 'ACCOUNT_SET';
export const ACCOUNT_FAILURE = 'ACCOUNT_FAILURE';

export const ERROR_AUTH_CLEAR = 'ERROR_AUTH_CLEAR';

export const CLEAR_SOCKETS = 'CLEAR_SOCKETS';
export const ADD_SOCKET = 'ADD_SOCKET';

export const VIEWS_REQUEST = 'VIEWS_REQUEST';
export const VIEWS_SET = 'VIEWS_SET';
export const VIEWS_FAILURE = 'VIEWS_FAILURE';

export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SET = 'USERS_SET';
export const USERS_FAILURE = 'USERS_FAILURE';

export const SET_LOCALE = 'SET_LOCALE';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';
export const PASSWORD_UPDATE_REQUEST = 'PASSWORD_UPDATE_REQUEST';
export const PASSWORD_UPDATE_SUCCESS = 'PASSWORD_UPDATE_SUCCESS';
export const PASSWORD_UPDATE_FAILURE = 'PASSWORD_UPDATE_FAILURE';
