export const CALL_API = 'CALL_API';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const COURSES_REQUEST = 'COURSES_REQUEST';
export const COURSES_SET = 'COURSES_SET';
export const COURSES_FAILURE = 'COURSES_FAILURE';
export const COURSE_ADD_REQUEST = 'COURSE_ADD_REQUEST';
export const COURSE_ADD_SUCCESS = 'COURSE_ADD_SUCCESS';
export const COURSE_ADD_FAILURE = 'COURSE_ADD_FAILURE';

export const LECTURES_REQUEST = 'LECTURES_REQUEST';
export const LECTURES_SET = 'LECTURES_SET';
export const LECTURES_FAILURE = 'LECTURES_FAILURE';
export const LECTURE_ADD_REQUEST = 'LECTURES_ADD_REQUEST';
export const LECTURE_ADD_SUCCESS = 'LECTURES_ADD_SUCCESS';
export const LECTURE_ADD_FAILURE = 'LECTURES_ADD_FAILURE';

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SET = 'COMMENTS_SET';
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE';

export const COMMENT_ADD_REQUEST = 'COMMENT_ADD_REQUEST';
export const COMMENT_ADD_SUCCESS = 'COMMENT_ADD_SUCCESS';
export const COMMENT_ADD_FAILURE = 'COMMENT_ADD_FAILURE';

export const ACCOUNT_REQUEST = 'ACCOUNT_REQUEST';
export const ACCOUNT_SET = 'ACCOUNT_SET';
export const ACCOUNT_FAILURE = 'ACCOUNT_FAILURE';
